IsMock: true
InterfaceInfo: 审批授权申请 WorkGrant/apply/approve
Method: POST
Fields: 
  - name: account
    info: 
     - rtype: string
     - isRequired: true
     - rdefault: aaa
  - name: bussinessId
    info:
     - rtype: string
     - isRequired: true
     - rdefault:
  - name: bussinessType
    info:
     - rtype: enum
     - isRequired: true
     - rdefault: 0 1
  - name: grantContent
    info:
     - rtype: string
     - isRequired: false
     - rdefault: 
  - name: status
    info:
     - rtype: enum
     - isRequired: false
     - rdefault: 
Response:
  - name: code
    info:
     - type: enum
     - default: 200
  - name: result
    info:
     - type: bool
     - default:
  - name: developerMsg
    info:
     - type: string
     - default:
  - name: requestId
    info:
     - type: string
     - default:
  - name: timestamp
    info:
     - type: string
     - default:
  - name: userMsg
    info:
     - type: string
     - default:
     