- id: "get-users"
  url: "/api-1/users"
  method: "GET"
  variants:
     - id: "success"
       options:
          request:
            headers:
            - "Content-Type:application/x-www-form-urlencoded"
            params:
            - "key:71e065a2cdf2753a5d6261b5002498b7"
            - "page:1"
          response:
            restype: "json"
            status: 200
            body:
            - "id:1"
            - "name:John Doe"